name: projectke3
description: "GRBK - Indie Coffee Shop Experience"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  
  # Network & Storage
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  
  # UI Components
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.2
  
  # Additional UI enhancements
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  pdf: ^3.11.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  intl: ^0.20.2
  web: ^1.1.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add assets when ready
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/