name: projectke3
description: "Aplikasi Penjualan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.2
  pocketbase: ^0.18.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
